import React, { useState, useEffect } from 'react';
import { AlertCircle, AlertTriangle, ShieldCheck, Info, Filter, Bell } from 'lucide-react';
import DemoBadge from '../components/DemoBadge';
import { fetchAlerts } from '../services/api';

export const AlertsPage = () => {
  const [alerts, setAlerts] = useState([]);
  const [filterSeverity, setFilterSeverity] = useState('ALL');

  useEffect(() => {
    fetchAlerts().then((res) => setAlerts(res.alerts || []));
  }, []);

  const filteredAlerts = alerts.filter(item => 
    filterSeverity === 'ALL' ? true : item.severity === filterSeverity
  );

  const getSeverityBadge = (severity) => {
    switch (severity) {
      case 'CRITICAL':
        return (
          <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-red-100 text-red-800 border border-red-200 flex items-center gap-1">
            <AlertCircle className="w-3.5 h-3.5 text-red-600" />
            CRITICAL
          </span>
        );
      case 'WARNING':
        return (
          <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-amber-100 text-amber-800 border border-amber-200 flex items-center gap-1">
            <AlertTriangle className="w-3.5 h-3.5 text-amber-600" />
            WARNING
          </span>
        );
      case 'INFO':
        return (
          <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-cyan-100 text-cyan-800 border border-cyan-200 flex items-center gap-1">
            <Info className="w-3.5 h-3.5 text-cyan-600" />
            INFO
          </span>
        );
      default:
        return <span className="px-2 py-0.5 rounded-md bg-slate-100 text-slate-700">{severity}</span>;
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8">
      
      {/* Prominent Demo Banner */}
      <DemoBadge variant="banner" text="DEMO DATA — All event notifications below are simulated for prototype testing." />

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight flex items-center gap-2">
              <Bell className="w-7 h-7 text-cyan-600" />
              System Event & Water Risk Alerts
            </h1>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Automated event telemetry generated by ESP32 verification routines and AI risk assessment module.
          </p>
        </div>

        {/* Severity Filters */}
        <div className="flex items-center gap-1.5 p-1 bg-slate-100 rounded-xl text-xs font-semibold">
          {['ALL', 'CRITICAL', 'WARNING', 'INFO'].map((sev) => (
            <button
              key={sev}
              onClick={() => setFilterSeverity(sev)}
              className={`px-3 py-1.5 rounded-lg transition-all ${
                filterSeverity === sev
                  ? 'bg-slate-900 text-white shadow-xs font-bold'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              {sev}
            </button>
          ))}
        </div>
      </div>

      {/* Alerts Table */}
      <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left text-slate-600">
            <thead className="bg-slate-50 text-slate-700 font-bold uppercase text-[10px] tracking-wider border-b border-slate-200">
              <tr>
                <th className="py-3 px-6">Alert ID</th>
                <th className="py-3 px-6">Timestamp</th>
                <th className="py-3 px-6">Severity</th>
                <th className="py-3 px-6">Event Title & Details</th>
                <th className="py-3 px-6">Source Module</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredAlerts.length > 0 ? (
                filteredAlerts.map((alert) => (
                  <tr key={alert.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="py-4 px-6 font-bold text-slate-900">{alert.id}</td>
                    <td className="py-4 px-6 text-slate-500 whitespace-nowrap">{alert.timestamp}</td>
                    <td className="py-4 px-6">{getSeverityBadge(alert.severity)}</td>
                    <td className="py-4 px-6 space-y-0.5">
                      <h4 className="font-bold text-slate-900 text-sm">{alert.title}</h4>
                      <p className="text-slate-500">{alert.message}</p>
                    </td>
                    <td className="py-4 px-6 text-slate-700 font-semibold">{alert.source}</td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="5" className="py-8 text-center text-slate-400">
                    No alerts match the selected severity filter.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
};

export default AlertsPage;
